services:
  postgres:
    image: postgres:16
    container_name: dbp-postgres

    environment:
      POSTGRES_DB: dbp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - dbp_data:/var/lib/postgresql/data

volumes:
  dbp_data: